"""Runtime cross-package import gate (auto-generated import list).

The list between the sentinels is generated by
`scitex-dev ecosystem install-cross-package-gate`; everything below the
closing sentinel is hand-owned and is NOT regenerated.

This test imports every cross-package module that 'scitex-str' references
in its source tree. Three outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- The peer DISTRIBUTION is absent (a lean install where the peer is
  genuinely not installed) → test is SKIPPED, via an `importorskip` on
  the ROOT package only.

The root/full-path split is the whole point and is what PS-140 checks.
`importorskip` on the FULL dotted path turns the second outcome into the
third: a renamed submodule reports as an absence, the test skips, and the
run reads green — so the gate cannot fail for the defect it exists to
catch. Banning the skip outright is not the fix either; PS-140's own
prose: that "would convert a legitimate absence into a hard failure — a
gate that cannot PASS, in place of one that cannot FAIL."
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_dev",
    "scitex_dict",
    "scitex_logging",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_module_name(module_name):
    """Importing scitex-str's declared cross-package dependency must yield a module object."""
    # Arrange — skip on the ROOT, and only on the ROOT, so that a missing
    # peer distribution skips while a rename inside a present one does not.
    root = module_name.split(".")[0]
    pytest.importorskip(root)
    # Act — a real import of the FULL dotted path. Not `find_spec`, which
    # only proves a module is FINDABLE, while the failures this gate exists
    # to catch happen at EXECUTION.
    module = importlib.import_module(module_name)
    # Assert
    assert module is not None


def test_cross_package_imports_list_is_iterable_sequence():
    """The CROSS_PACKAGE_IMPORTS constant is a list (the gate has a schema)."""
    # Arrange
    declared = CROSS_PACKAGE_IMPORTS
    # Act
    is_list = isinstance(declared, list)
    # Assert
    assert is_list is True
